# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/ark/benefit/setup-makefiles.sh

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/ark/benefit/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/ark/benefit/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/ark/benefit/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/ark/benefit/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/ark/benefit/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/ark/benefit/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/ark/benefit/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/ark/benefit/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/ark/benefit/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/ark/benefit/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/ark/benefit/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/ark/benefit/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/ark/benefit/proprietary/bin/vm_bms:system/bin/vm_bms \
    vendor/ark/benefit/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/ark/benefit/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/ark/benefit/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
   vendor/ark/benefit/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/ark/benefit/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/ark/benefit/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    vendor/ark/benefit/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_gc2355_back_common.so:system/vendor/lib/libchromatix_gc2355_back_common.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_gc2355_back_preview.so:system/vendor/lib/libchromatix_gc2355_back_preview.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_gc2355_front_1lane_common.so:system/vendor/lib/libchromatix_gc2355_front_1lane_common.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_gc2355_front_1lane_preview.so:system/vendor/lib/libchromatix_gc2355_front_1lane_preview.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_gc2355_front_common.so:system/vendor/lib/libchromatix_gc2355_front_common.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_gc2355_front_preview.so:system/vendor/lib/libchromatix_gc2355_front_preview.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_common.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_common.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_default_video.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_default_video.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_hfr_120fps.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_hfr_120fps.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_hfr_60fps.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_hfr_60fps.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_hfr_90fps.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_hfr_90fps.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_liveshot.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_liveshot.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_preview.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_preview.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_snapshot.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_snapshot.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_back_video_hd.so:system/vendor/lib/libchromatix_s5k4h5_8916_back_video_hd.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_common.so:system/vendor/lib/libchromatix_s5k4h5_8916_common.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_default_video.so:system/vendor/lib/libchromatix_s5k4h5_8916_default_video.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_hfr_120fps.so:system/vendor/lib/libchromatix_s5k4h5_8916_hfr_120fps.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_hfr_60fps.so:system/vendor/lib/libchromatix_s5k4h5_8916_hfr_60fps.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_hfr_90fps.so:system/vendor/lib/libchromatix_s5k4h5_8916_hfr_90fps.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_liveshot.so:system/vendor/lib/libchromatix_s5k4h5_8916_liveshot.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_preview.so:system/vendor/lib/libchromatix_s5k4h5_8916_preview.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_snapshot.so:system/vendor/lib/libchromatix_s5k4h5_8916_snapshot.so \
    vendor/ark/benefit/proprietary/vendor/lib/libchromatix_s5k4h5_8916_video_hd.so:system/vendor/lib/libchromatix_s5k4h5_8916_video_hd.so \
    vendor/ark/benefit/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/ark/benefit/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_gc2355_back.so:system/vendor/lib/libmmcamera_gc2355_back.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_gc2355_front.so:system/vendor/lib/libmmcamera_gc2355_front.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_gc2355_front_1lane.so:system/vendor/lib/libmmcamera_gc2355_front_1lane.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_s5k4h5_8916.so:system/vendor/lib/libmmcamera_s5k4h5_8916.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmcamera_s5k4h5_8916_back.so:system/vendor/lib/libmmcamera_s5k4h5_8916_back.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/ark/benefit/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/ark/benefit/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/ark/benefit/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/ark/benefit/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/ark/benefit/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/ark/benefit/proprietary/vendor/lib/libjni_livedisplay.so:system/vendor/lib/libjni_livedisplay.so \
    vendor/ark/benefit/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/ark/benefit/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/ark/benefit/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/ark/benefit/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/ark/benefit/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/ark/benefit/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/ark/benefit/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/ark/benefit/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/ark/benefit/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/ark/benefit/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/ark/benefit/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/ark/benefit/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/ark/benefit/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/ark/benefit/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/ark/benefit/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/ark/benefit/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/ark/benefit/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/ark/benefit/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/ark/benefit/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/ark/benefit/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    vendor/ark/benefit/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/ark/benefit/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/ark/benefit/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/ark/benefit/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/ark/benefit/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/ark/benefit/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/ark/benefit/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/ark/benefit/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/ark/benefit/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/ark/benefit/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/ark/benefit/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/ark/benefit/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/ark/benefit/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/ark/benefit/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/ark/benefit/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/ark/benefit/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/ark/benefit/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/ark/benefit/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/ark/benefit/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/ark/benefit/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/ark/benefit/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/ark/benefit/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/ark/benefit/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/ark/benefit/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/ark/benefit/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/ark/benefit/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/ark/benefit/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/ark/benefit/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/ark/benefit/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/ark/benefit/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/ark/benefit/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/ark/benefit/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/ark/benefit/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/ark/benefit/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/ark/benefit/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/ark/benefit/proprietary/bin/radish:system/bin/radish \
    vendor/ark/benefit/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/ark/benefit/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/ark/benefit/proprietary/etc/permissions/com.qrd.wappush.xml:system/etc/permissions/com.qrd.wappush.xml \
    vendor/ark/benefit/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/ark/benefit/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/ark/benefit/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/ark/benefit/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/ark/benefit/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/ark/benefit/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/ark/benefit/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/ark/benefit/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/ark/benefit/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/ark/benefit/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/ark/benefit/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/ark/benefit/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/ark/benefit/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/ark/benefit/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/ark/benefit/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/ark/benefit/proprietary/lib/libwcnss_qmi.so:system/lib/libwcnss_qmi.so
endif

PRODUCT_COPY_FILES += \
    vendor/ark/benefit/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/ark/benefit/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/ark/benefit/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/ark/benefit/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/ark/benefit/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/ark/benefit/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/ark/benefit/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt
